name: github_client
description: A library github_client.
version: 0.0.1
repository: https://github.com/azkadev/azkadev.git
issue_tracker: https://github.com/azkadev/azkadev.git
homepage: https://youtube.com/@azkadev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:  
  galaxeus_lib: ^0.0.71
  http: ^0.13.6
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
